// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnghV_MbJG6llwCMvvqZOqfSgXBLWVYHs',
    appId: '1:248178975857:web:057cad9d430c8faac067d0',
    messagingSenderId: '248178975857',
    projectId: 'pokeproject-pokeapi',
    authDomain: 'pokeproject-pokeapi.firebaseapp.com',
    storageBucket: 'pokeproject-pokeapi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM5RXLKMB7cpbR0QpBd7fkMJ8K3QreDLQ',
    appId: '1:248178975857:android:c12b0ffd783e8d39c067d0',
    messagingSenderId: '248178975857',
    projectId: 'pokeproject-pokeapi',
    storageBucket: 'pokeproject-pokeapi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7wXEhEZicwzvnbhfia__KGPOUxcfMrsw',
    appId: '1:248178975857:ios:c3d49fcf99213490c067d0',
    messagingSenderId: '248178975857',
    projectId: 'pokeproject-pokeapi',
    storageBucket: 'pokeproject-pokeapi.firebasestorage.app',
    iosBundleId: 'com.example.appTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7wXEhEZicwzvnbhfia__KGPOUxcfMrsw',
    appId: '1:248178975857:ios:c3d49fcf99213490c067d0',
    messagingSenderId: '248178975857',
    projectId: 'pokeproject-pokeapi',
    storageBucket: 'pokeproject-pokeapi.firebasestorage.app',
    iosBundleId: 'com.example.appTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnghV_MbJG6llwCMvvqZOqfSgXBLWVYHs',
    appId: '1:248178975857:web:3473433355eb14b3c067d0',
    messagingSenderId: '248178975857',
    projectId: 'pokeproject-pokeapi',
    authDomain: 'pokeproject-pokeapi.firebaseapp.com',
    storageBucket: 'pokeproject-pokeapi.firebasestorage.app',
  );
}
